blank_issues_enabled: true
contact_links:
  - name: Undal Core Security Policy
    url: https://github.com/undal/undal/blob/master/SECURITY.md
    about: View security policy
  - name: Undal Core Developers
    url: https://bitcoincore.org
    about: Undal Core homepage
